// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzapohG1P3xEUPUUuFyjvhnvnh4Ggl0ak',
    appId: '1:310773989407:web:aafbd22a91cf052215d52a',
    messagingSenderId: '310773989407',
    projectId: 'gdsc-project-2',
    authDomain: 'gdsc-project-2.firebaseapp.com',
    storageBucket: 'gdsc-project-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiwsHHdj0Dl9aKg1-28XrXiu527v3Xs4g',
    appId: '1:310773989407:android:03056826488ef17415d52a',
    messagingSenderId: '310773989407',
    projectId: 'gdsc-project-2',
    storageBucket: 'gdsc-project-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_fLtIu0ChLUAO391LNV0Z4jwkx5Sy2pU',
    appId: '1:310773989407:ios:8a738e65d12dfef915d52a',
    messagingSenderId: '310773989407',
    projectId: 'gdsc-project-2',
    storageBucket: 'gdsc-project-2.appspot.com',
    iosClientId: '310773989407-kmlv56hs666np8vhurri9ptnnvfam4j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_fLtIu0ChLUAO391LNV0Z4jwkx5Sy2pU',
    appId: '1:310773989407:ios:7254f2add623aa7715d52a',
    messagingSenderId: '310773989407',
    projectId: 'gdsc-project-2',
    storageBucket: 'gdsc-project-2.appspot.com',
    iosClientId: '310773989407-kc0ash7815naqra3nclcab2l9dg01afh.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp.RunnerTests',
  );
}
